# Generated by Django 5.2.8 on 2025-11-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField()),
                ('ok', models.TextField()),
                ('response', models.JSONField()),
            ],
        ),
    ]
