# Generated by Django 5.2.8 on 2025-11-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clima',
            name='url',
            field=models.TextField(default='url'),
        ),
    ]
