# Generated by Django 5.2.8 on 2025-11-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clima_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medicao', models.DateTimeField()),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('precipitacao', models.FloatField(blank=True, null=True)),
                ('vento', models.FloatField(blank=True, null=True)),
                ('clima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='api.clima')),
            ],
        ),
    ]
